<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{{ env('APP_NAME')}} Report</title>
</head>
<style>
  body {
    margin: 1rem;
    font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif
  }
  .container {
    max-width: 1024px;
    margin-inline: auto
  }
  table {
    table-layout: fixed;
    width: 100%;
    text-align: left;
    border-collapse: collapse;
    border: 1px solid rgb(128, 128, 128)
  }

  tr {
    border: 1px solid rgb(123, 123, 123);
  }

  th, td {
    padding: .75rem;
    text-transform: capitalize;
  }
</style>
<body>
  <div class="container">
    <div style="text-align: center; margin-bottom: 4rem">
      <h1>{{ env('APP_NAME')}} Report</h1>
      <p>From: {{date('Y-m-d',strtotime($start))}}, To: {{date('Y-m-d',strtotime($end))}}</p>
      <p>Generated By: {{auth()->user()->name}}</p>
    </div>
    <table>
      <thead>
        <tr>
          <th>Customer</th>
          <th>Car</th>
          <th>Sales Person</th>
          <th>Date</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        @forelse ($appointments as $appointment)
            <tr>
              <td>{{$appointment->customer->name}}</td>
              <td>{{$appointment->car->name}}</td>
              <td>{{$appointment->salesPerson->name}}</td>
              <td>{{$appointment->date}}</td>
              <td><span style="padding: .25rem .5rem; border: .5px solid gray;border-radius: 5px"> {{$appointment->status}}</span></td>
            </tr>
        @empty
            
        @endforelse

      </tbody>
    </table>
  </div>
</body>
</html>